version: '3.8'

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    extra_hosts:
      - "localhost:host-gateway"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: productos_db
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  
    healthcheck:
      test: ["CMD-SHELL", "mysql -u root -e 'SELECT 1;'"]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 15s

volumes:
  mysql_data: